### PR TITLE
Make Auto-Configuration expose explicit DataSource type

### LINKED ISSUE #4673: Auto-Configuration should expose explicit datasource type, not interface
The following auto-configuration exposes a bean of type `javax.sql.DataSource` and provide an explicit initialization method on it:

https://github.com/alibaba/druid/blob/f937ecd43363b2df61afdc120858097cb2510580/druid-spring-boot-starter/src/main/java/com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.java#L53-L58

`javax.sql.DataSource` does not have an method named `init` so introspecting the bean definition at build time is failing. Please expose the actual type rather than the interface.

### PR DESCRIPTION
**Pull request by linghengqian**
- Fix #4673
- Make Auto-Configuration expose concrete data source types

### CODE REVIEW

**Comment by linghengqian** [comment]
Any hints for me to push the merge of this PR?

**Comment by linghengqian** [comment]
@wenshao Any hints for me to push the merge of this PR?

**Comment by linghengqian** [comment]
@wenshao Can you approve the CI/CD process？

**Comment by linghengqian** [comment]
@wenshao Can you approve the CI/CD process？

**Comment by linghengqian** [comment]
@VictorZeng Can you approve the CI and review the changes?

**Comment by linghengqian** [comment]
@wenshao Can you review the changes?

**Comment by linghengqian** [comment]
@wenshao Can you review the changes?

**Comment by zrlw** [comment]
In accordance with practice，the return type of dataSource auto configuration method should always be DataSource.
The essence of the issue is duplication of initial methods. the initMethod attribute of DruidDataSourceWrapper bean is redudant as DruidDataSourceWrapper is already a InitializingBean.
it will be ok that calling init method at the end of DruidDataSourceWrapper#afterPropertiesSet and removing initMethod attribute  from it's auto configuration method.

**Comment by zrlw** [comment]
it might be better using PR #5603

**Comment by linghengqian** [comment]
> it might be better using PR #5603 

- I haven't looked at the issue in a long time, so I will say that I have no idea whether Alibaba Druid can be used under GraalVM Native Image now.  Thanks for the PR.

**Pull request closed without merging**
